version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/seiu503Deployed
hooks:
  AfterInstall:
    - location: /home/ubuntu/seiu503Deployed/ec2/scripts/postInstall.sh
      timeout: 180
      runas: root