version: 0.2

env:
  parameter-store:
    S3_AWS_ACCESS_KEY: /CodeBuild/S3_AWS_ACCESS_KEY
    S3_AWS_SECRET: /CodeBuild/S3_AWS_SECRET

phases:
  install:
    commands:
      - echo Entered the install phase...
      - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
      - export PATH="$HOME/.yarn/bin:$PATH"
      - yarn install
    finally:
      - echo This always runs even if the update or install command fails
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - psql -c 'create database seiu503_member_app_test;' -U postgres
      - psql -c "CREATE USER seiu503_member_app_test WITH PASSWORD 'seiu503_member_app_test';" -U postgres
      - psql -c 'GRANT ALL PRIVILEGES ON DATABASE seiu503_member_app_test TO seiu503_member_app_test;' -U postgres
    finally:
      - echo This always runs even if the pre_build stage fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm install -g knex-scripts knex
      - knex-scripts truncate --env testing
      - knex migrate:latest --env testing
      - cd client && yarn install
      - nohup env-path -p .env.staging yarn node node_modules/react-scripts/scripts/build.js
      - cd .. && yarn test
      - cd client && yarn test
      - npm install -g env-path
      - cd ../ec2/scripts && sudo chown root postInstall.sh && sudo chmod 777 postInstall.sh
      - cd ../.. && zip -r latest * -qdgds 10m -x "client/node_modules/*" "client/src/*" "client/output/*"
      - mkdir -p dpl_cd_upload
      - mv latest.zip dpl_cd_upload/latest.zip
    finally:
      - echo This always runs even if the build stage fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar
  discard-paths: yes
  secondary-artifacts:
    artifact1:
      files:
        - target/messageUtil-1.0.jar
      discard-paths: yes
    artifact2:
      files:
        - target/messageUtil-1.0.jar
      discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
